"""api key encrypted secret

Revision ID: bd21e870fe70
Revises: 1af5b8e3f663
Create Date: 2026-08-27 13:07:06.989186
"""
from alembic import op
import sqlalchemy as sa


revision = 'bd21e870fe70'
down_revision = '1af5b8e3f663'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_enc', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('secret_enc')

    # ### end Alembic commands ###
