"""global settings

Revision ID: d4973a759cab
Revises: bd21e870fe70
Create Date: 2026-08-28 11:21:38.266417
"""
from alembic import op
import sqlalchemy as sa


revision = 'd4973a759cab'
down_revision = 'bd21e870fe70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###
